### ISSUE TITLE
Add workspaces support

### ISSUE THREAD

**Issue by jdalton** [SocketDev/socket-cli#235]
For this we need to glob the workspaces and update the package.json's.

**Comment by moltar** [comment]
FYI this repo has a few workspace-related packages that are of high quality: https://github.com/saqqdy/node-kit

**Comment by jdalton** [comment]
@moltar Can you try with https://www.npmjs.com/package/socket v0.14.18+

**Comment by jdalton** [comment]
@molar after reading a bit more I see I've not quite implemented it.

**Comment by jdalton** [comment]
Ok @moltar I've added support though I don't feel very confident about it. I ran into a bad pnpm install and had to uninstall and re-install. I know it's scanning workspaces but for node-kit for example it didn't add anything to its individual workspace packages.

**Comment by moltar** [comment]
Yeah, out of 53 packages in the monorepo, it modified 3. But I think almost every package should have _some_ old packages in it, as they are all around the same topic.

**Comment by jdalton** [comment]
I found the issue. `pnpm` is pruning results. I've opened a PR to fix it: https://github.com/pnpm/pnpm/pull/8729

**Comment by jdalton** [comment]
@moltar Actually, in our usage I think we avoid that issue _(or at first glance)_. The pruning of dependencies happens when you pass other packages to the `list` command, `pnpm ls "@company-scope/**"` but we don't do that. I wonder if because it's a workspace package if behind the scenes it's doing something. Will dig into it more and report back.

**Comment by jdalton** [comment]
@moltar Fixed it _(independently of the pnpm issue)_

**Comment by moltar** [comment]
That indeed have worked and fixed _every_ package in the repo. 😁 

Thank you!! 🎉

**Comment by moltar** [comment]
Ah, nooes, spoke too soon!

> packages/facts                           |  WARN  The field "resolutions" was found in /.../packages/facts/package.json. This will not take effect. You should configure "resolutions" at the root of the workspace instead.

I think I mentioned it in my earlier issue is that pnpm _hoists_ everything to root `package.json`. And to apply the fixes to a specific package, need to use a funky syntax `qar@1>zoo`.

Docs: https://pnpm.io/package_json#pnpmoverrides

**Comment by jdalton** [comment]
This looks to be by design. In this case everything is already hoisted in the root (the root has all the overrides). We specify the "resolutions" field in the workspace package because when the package is published to npm it will need the `resolutions` field to be usable by `yarn`, `bun`, and `pnpm` and the `overrides` field is for npm.
