### ISSUE TITLE
What happened to GitHub Releases?

### ISSUE THREAD

**Issue by aarongoldenthal** [SocketDev/socket-cli#265]
It's really helpful to have GitHub releases, with release notes, to know what has changed without having to dig through git commits. I'm not sure why that practice stopped in September, but it would be great if it could be brought back.

**Comment by jdalton** [comment]
@aarongoldenthal Thanks for opening an issue. I'll see about back dating some of the big ones. The rest have been created with commit ranges to browse through the Release GitHub UI.
